packages:
  - "."
  - "server"
allowBuilds:
  '@firebase/util': true
  '@google/genai': true
  '@whiskeysockets/baileys': true
  esbuild: true
  onnxruntime-node: true
  protobufjs: true
  puppeteer: true
  sharp: true
  youtube-dl-exec: true
